// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace LoginTest.Models
{
    public partial class LogintestdbContext : DbContext
    {
        public LogintestdbContext()
        {
        }

        public LogintestdbContext(DbContextOptions<LogintestdbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<User> User { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.
                optionsBuilder.UseSqlServer("Data Source=LAPTOP-K3DT06D7\\SQLEXPRESS;Initial Catalog=LoginTestDb;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity<User>(entity =>
            {
                entity.HasKey(e => e.LoginName)
                    .HasName("PK_User_UserID");

                entity.Property(e => e.LoginName).ValueGeneratedNever();

                entity.Property(e => e.Salt).HasDefaultValueSql("(newid())");

                entity.Property(e => e.UserID).ValueGeneratedOnAdd();
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}