// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LoginTest.Models
{
    public partial class User
    {
        public long UserID { get; set; }
        [StringLength(40)]
        public string LoginName { get; set; }
        [Required]
        [MaxLength(64)]
        public byte[] PasswordHash { get; set; }
        [StringLength(40)]
        public string FirstName { get; set; }
        [StringLength(40)]
        public string LastName { get; set; }
        public Guid? Salt { get; set; }
    }
}